"""empty message

Revision ID: ee30bc68e8b3
Revises: 66b4fe0ca12b
Create Date: 2019-03-10 18:15:23.678441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee30bc68e8b3'
down_revision = '66b4fe0ca12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('people', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='words_pkey')
    )
    # ### end Alembic commands ###
